---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft-java
      version: 10.1.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-minecraft"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    service:
     main:
       enabled: true
       loadBalancerIP: ${MINECRAFT_IP}
       type: LoadBalancer
       ports:
         main:
           enabled: true
           protocol: tcp
           port: 25565
         query:
           enabled: true
           protocol: udp
           port: 25565
     rcon:
       enabled: true
       loadBalancerIP: ${MINECRAFT_IP}
       type: LoadBalancer
       ports:
         rcon:
           enabled: true
           port: 25575
    
    mcbackup:
     enabled: false
     initial_delay: 2m
     backup_interval: 24h
     player_online_check_interval: 5m
     prune_backups_days: 7
     pause_if_no_players: false
     link_latest: false
     # values gzip,bzip2,zstd
     tar_compress_method: gzip
     # White spaced separated list
     zstd_params:
       - --long=25
       - --single-thread
     # comma separated list
     excludes:
       - "*.jar"
       - "cache"
       - "logs"
       - "*.tmp"
    
    workload:
     main:
       podSpec:
         containers:
           main:
             imageSelector: j21Image
             env:
               ENABLE_QUERY: "true"
               OVERRIDE_SERVER_PROPERTIES: true
               VERSION: "LATEST"
               TYPE: "VANILLA"
               DIFFICULTY: easy
               MAX_PLAYERS: 20
               MAX_WORLD_SIZE: 10000
               ALLOW_NETHER: true
               ANNOUNCE_PLAYER_ACHIEVEMENTS: true
               ENABLE_COMMAND_BLOCK: false
               FORCE_GAMEMODE: false
               GENERATE_STRUCTURES: true
               HARDCORE: false
               MAX_BUILD_HEIGHT: 256
               MAX_TICK_TIME: 60000
               SPAWN_ANIMALS: true
               SPAWN_MONSTERS: true
               SPAWN_NPCS: true
               VIEW_DISTANCE: 16
               MODE: survival
               MOTD: "Welcome to Six-Shooter Minecraft"
               PVP: false
               LEVEL_TYPE: DEFAULT
               LEVEL: world
               ONLINE_MODE: true
               MEMORY: 2048M
               RCON_PASSWORD:  ${MC_RCON_PASS}
               # PACKWIZ_URL: ""
               # CUSTOM_SERVER: ""
               # QUILT_LOADER_VERSION: ""
               # QUILT_LAUNCHER: ""
               # QUILT_LAUNCHER_URL: ""
               # PUFFERFISH_BUILD: "lastSuccessfulBuild"
               # FORGEVERSION: ""
               # FORGE_INSTALLER: ""
               # FORGE_INSTALLER_URL: ""
               # FABRIC_LOADER_VERSION: ""
               # FABRIC_INSTALLER: ""
               # FABRIC_INSTALLER_URL: ""
               # SPIGOT_DOWNLOAD_URL: ""
               # BUILD_FROM_SOURCE: false
               # BUKKIT_DOWNLOAD_URL: ""
               # PAPERBUILD: ""
               # PAPER_DOWNLOAD_URL: ""
               # AIRPLANE_BUILD: "lastSuccessfulBuild"
               # MAGMA_CHANNEL: "stable"
               # MOHIST_BUILD: ""
               # CANYON_BUILD: ""
               # SPONGEBRANCH: "STABLE"
               # SPONGEVERSION: ""
               # LIMBO_BUILD: "LATEST"
               # LIMBO_SCHEMA_FILENAME: "default.schem"
               # CRUCIBLE_RELEASE: "latest"
               # FTB_MODPACK_ID: ""
               # FTB_MODPACK_VERSION_ID: ""
               # CF_SERVER_MOD: ""
               # CF_BASE_DIR: ""
               # USE_MODPACK_START_SCRIPT: true
               # FTB_LEGACYJAVAFIXER: false
               # WHITELIST: ""
               # OPS: ""
               # ICON: ""
               # SEED: ""
               # GENERATOR_SETTINGS: ""
               # WORLD: ""
               # FORCE_REDOWNLOAD: false
               # USE_FLARE_FLAGS: false
               # USE_AIKAR_FLAGS: true
               # USE_SIMD_FLAGS: false
               # JVM_OPTS: ""
               # JVM_XX_OPTS: ""
               # CF_API_KEY
               # CF_PAGE_URL
               # CF_SLUG
               # CF_EXCLUDE_INCLUDE_FILE
               # CF_EXCLUDE_MODS
               # CF_FORCE_INCLUDE_MODS
               # CF_FORCE_SYNCHRONIZE
               # CF_OVERRIDES_SKIP_EXISTING
               # CF_PARALLEL_DOWNLOADS
               # CF_SET_LEVEL_FROM
     mcbackup:
       enabled: true
       type: Deployment
       podSpec:
         containers:
           mcbackup:
             primary: true
             enabled: true
             imageSelector: mcBackupImage
             probes:
               liveness:
                 enabled: false
               readiness:
                 enabled: false
               startup:
                 enabled: false
    
    persistence:
     data:
       volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              accessModes:
                - ReadWriteOnce
              enabled: false
            src:
              enabled: false
       enabled: true
       targetSelector:
         main:
           main:
             mountPath: /data
         mcbackup:
           mcbackup:
             mountPath: /data
             readOnly: true
     backups:
       volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              accessModes:
                - ReadWriteOnce
              enabled: false
            src:
              enabled: false
       enabled: true
       targetSelector:
         mcbackup:
           mcbackup:
             mountPath: /backups


